### ISSUE TITLE
Should we opensource workflows?

### ISSUE THREAD

**Issue by jacknoble** [doximity/simplekiq#6]
I think we should -- it was part of our original vision and helps solve the same set of problems. But we probably should first make significant changes -- mainly because there is a lot of random code in there that none of us understand. 

Also while tree-view can definitely be helpful it probably shouldn't be the primary view since the raison d'être of simplekiq is enable you to think of your background code as a sequential flow. This view would be more orchestration, leveraging knowledge of orchestrations to flatten the tree based on orchestration callbacks, hiding jobs that aren't user-owned and leveraging orchestration "checkpoints" if we build those out. These two views can share some underlying abstractions but separating them also means you could use Simplekiq workflows without Orchestrations.

**Comment by jcwilk** [comment]
The workflows tool would require too much rewriting to release for it to be worth it unfortunately, it just has really bad performance for workflows with more than a few thousand jobs and sidekiq/sidekiq-pro/simplekiq are very much designed to handle things of that scale. Our other workflow tracking tool is far too Campaigns-specific, so going to close this for now as we don't have plans to make a reasonable path towards this any time soon.
